<a href="https://colab.research.google.com/github/beliabaez/CE888_2020/blob/master/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Quiestion **1** Create a (4x2) integer array and prit it's attributes


In [0]:
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import normalize

In [0]:

a = np.array([[ 0, 1],
              [2, 3],
              [10,11],
              [12,13]])
print(a)

[[ 0  1]
 [ 2  3]
 [10 11]
 [12 13]]


Question **2** Create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
a = np.array([0, 5, 8, 3, 4, 1, 2, 6, 7, 9])
print(a)
#sorting numbers in ascending
a.sort()
print(a)
#sort numbers in descending
d = a[::-1]
print(d)


[0 5 8 3 4 1 2 6 7 9]
[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]


question **3** Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [106]:
b = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(b)

#slicing array
A = np.reshape(b,(-1,3))


print (A)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Question **4**  Stack two arrays of any size horizontally and vertically

In [0]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#stack horizontally
d = np.stack((a,b), axis=1)
print("Horizontally")
print (d)
#stack vertically
d = np.stack((a,b), axis=0)
print("Vertically")
print (d)

Horizontally
[[1 4]
 [2 5]
 [3 6]]
Vertically
[[1 2 3]
 [4 5 6]]


Question **5** Create two array of same size and find commom elements

In [0]:
a = [8, 6, 4, 7, 9, 5]
b = [1, 2, 3, 4, 5, 6]

print (a)
print (b)
print ("Commom Elements")
print (set(a) & set (b))

[8, 6, 4, 7, 9, 5]
[1, 2, 3, 4, 5, 6]
Commom Elements
{4, 5, 6}


Question **6** Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [0]:
a = np.array([[1, 2, 8, 9, 8],
             [8, 4, 5, 6, 7],
             [6, 7, 0, 3, 1],
             [8, 9, 7, 4, 2],
             [1, 6, 2, 1, 6]])

b= np.array([[1, 2, 8, 9, 8],
             [8, 2, 5, 6, 7],
             [6, 7, 0, 10, 1],
             [8, 9, 7, 4, 2],
             [1, 6, 2, 1, 6]])

#per columns
print (a.min(0))
print (a.max(0))

#per rows
print (a.min(1))
print (a.max(1))

[1 2 0 1 1]
[8 9 8 9 8]
[1 4 0 2 1]
[9 8 7 9 6]


Question **7** Create an array of size 100 and compute the mean, median, standard deviation.

In [0]:
a = np.random.rand(1, 99)
d = np.mean(a)
e = np.median(a)
f = np.std(a)

print("mean", d)
print("median", e)
print("standar deviation", f)


mean 0.49386183447229043
median 0.4855233542224826
standar deviation 0.26953544305785015


Question **8** Normalize a 5x5 random matrix

In [0]:
x = np.random.rand(5,5)
b = normalize(x, copy=False)
print(b)



[[0.71829182 0.31702    0.48366378 0.33039138 0.2011618 ]
 [0.41989881 0.27563252 0.40094841 0.69401288 0.32449685]
 [0.53333869 0.64716313 0.37976843 0.37539493 0.10763042]
 [0.43769324 0.09920353 0.11922024 0.86319634 0.19814615]
 [0.24167134 0.29146989 0.292488   0.6920338  0.54053701]]


Question **9** Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [0]:
a = np.random.rand(4,4,3)
b = np.random.rand(4,4)

b.dot(b.T)


array([[0.95971008, 0.70576949, 1.28285376, 0.91298237],
       [0.70576949, 1.1926561 , 1.27665106, 1.29843717],
       [1.28285376, 1.27665106, 2.46708741, 1.56968362],
       [0.91298237, 1.29843717, 1.56968362, 1.55209396]])